<?php
return array(
    'title'=>'创蓝',
    'options'=>array(
        'sys_user'=>array(
            'title'=>'帐号:',
            'type'=>'text',
            'value'=>'90040',
            'tip'=>'创蓝账号'
        ),
        'sys_pass'=>array(
            'title'=>'密码:',
            'type'=>'password',
            'value'=>'90040',
            'tip'=>'创蓝密码'
        ),
    ),
    'version'=>'1.0',
    'author'=>'七朵云',
    'value'=>'0',
);